# =============================================================================
# language_adapter_base.py
# =============================================================================
# PURPOSE:
#   Abstract base class (interface contract) that every language adapter
#   must implement. Currently Java 8 is the only concrete adapter, but this
#   design allows future addition of Java 18, Kotlin, Groovy etc. by simply
#   creating a new class that inherits from LanguageAdapter and implementing
#   all the methods below.
#
# WHAT IT CONTAINS:
#   - class LanguageAdapter
#       configure()    : sets up shared state and caches for the adapter
#       file_extension(): returns the file extension e.g. ".java"
#       parse_ast()    : parses source code into an AST
#       get_declared_types()    : lists all classes/interfaces in an AST
#       get_methods_in_type()   : lists all methods in a type node
#       extract_method_metadata(): returns annotations, return type, params
#       find_calls_in_method()  : finds all method calls inside a method
#       fallback_parse()        : regex fallback when AST parse fails
#       is_system_call()        : checks if a call is a JDK/library call
#       language_keywords()     : returns reserved keyword set
#       build_object_class_map(): maps variable names to class types
#       build_method_return_index(): maps class->method->return type
#       find_type_to_file_map() : maps class names to source file paths
#       extract_method_loc()    : counts lines of code for a method
#       extract_application_properties_from_folder(): reads config values
#
# WHEN TO EDIT THIS FILE:
#   Only when adding a brand new capability that ALL adapters must support.
#   Adding a new language: create a new file, inherit from LanguageAdapter,
#   implement all methods - do NOT edit this file.
#
# DEPENDS ON: Nothing
# USED BY:    java_ast_parser.py, java_call_resolver.py,
#             java_project_indexer.py, java_property_extractor.py,
#             lineage_engine.py
# =============================================================================

class LanguageAdapter:
    """
    Base interface for language-specific adapters.
    Concrete adapters (Java8Adapter, etc.) must implement these methods.
    """
    def configure(self, *, details, regex,
                  include_unqualified=True,
                  accept_local_new_types=True,
                  accept_parameter_types=True,
                  accept_same_package=True,
                  file_content_cache=None,
                  raw_ast_cache=None):
        self.details = details
        self.regex = regex
        self.include_unqualified = include_unqualified
        self.accept_local_new_types = accept_local_new_types
        self.accept_parameter_types = accept_parameter_types
        self.accept_same_package = accept_same_package
        # Shared caches so adapter index-builders never re-read a file
        self._file_content_cache = file_content_cache if file_content_cache is not None else {}
        self._raw_ast_cache = raw_ast_cache if raw_ast_cache is not None else {}

    def file_extension(self):
        raise NotImplementedError

    def parse_ast(self, code):
        raise NotImplementedError

    def get_declared_types(self, ast):
        raise NotImplementedError

    def get_methods_in_type(self, type_node):
        raise NotImplementedError

    def extract_method_metadata(self, method_node):
        raise NotImplementedError

    def find_calls_in_method(self, type_node, method_node, code):
        raise NotImplementedError

    def fallback_parse(self, code_raw):
        raise NotImplementedError

    def is_system_call(self, call):
        raise NotImplementedError

    def language_keywords(self):
        raise NotImplementedError

    def build_object_class_map(self, app_folder):
        raise NotImplementedError

    def build_method_return_index(self, app_folder):
        raise NotImplementedError

    def find_type_to_file_map(self, app_folder):
        raise NotImplementedError

    def extract_method_loc(self, file_path, method_name):
        raise NotImplementedError

    def extract_application_properties_from_folder(self, app_folder):
        raise NotImplementedError
